version: "3.8"

services:

  api-letmeask:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: api-letmeask
    command: yarn dev
    env_file:
      - .env
    volumes:
     - .:/api-letmeask
    depends_on:
     - database
    ports:
      - 3333:3333

  database:
    image: mariadb
    container_name: maria-db-api-letmeask
    restart: always
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: mariadb